"""followers

Revision ID: 685fb55c3414
Revises: cbe4f5436e36
Create Date: 2020-07-28 10:49:41.648780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685fb55c3414'
down_revision = 'cbe4f5436e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
